// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvYKHcbFVFH1XUsTyFMc8m8ptma3xmHsU',
    appId: '1:262536826202:web:93160fca1f09fd98e07763',
    messagingSenderId: '262536826202',
    projectId: 'test2024-10932',
    authDomain: 'test2024-10932.firebaseapp.com',
    storageBucket: 'test2024-10932.appspot.com',
    measurementId: 'G-KY4Y73Z4VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeM4-gnQamAQZvZcfPOAo0ck7HlhudIBY',
    appId: '1:262536826202:android:a979190dd28a91e5e07763',
    messagingSenderId: '262536826202',
    projectId: 'test2024-10932',
    storageBucket: 'test2024-10932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASoxmpAkqlPttVr5dj3AE2X0QMMYSNWvk',
    appId: '1:262536826202:ios:b1c28d0da519f3e0e07763',
    messagingSenderId: '262536826202',
    projectId: 'test2024-10932',
    storageBucket: 'test2024-10932.appspot.com',
    iosBundleId: 'com.example.vintedProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASoxmpAkqlPttVr5dj3AE2X0QMMYSNWvk',
    appId: '1:262536826202:ios:b1c28d0da519f3e0e07763',
    messagingSenderId: '262536826202',
    projectId: 'test2024-10932',
    storageBucket: 'test2024-10932.appspot.com',
    iosBundleId: 'com.example.vintedProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvYKHcbFVFH1XUsTyFMc8m8ptma3xmHsU',
    appId: '1:262536826202:web:2f6b6ff90ae4ec84e07763',
    messagingSenderId: '262536826202',
    projectId: 'test2024-10932',
    authDomain: 'test2024-10932.firebaseapp.com',
    storageBucket: 'test2024-10932.appspot.com',
    measurementId: 'G-J2BB2MZXXG',
  );
}
